// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twkjzdcvfvqrljxfurcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3a2p6ZGN2ZnZxcmxqeGZ1cmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDQ0OTEsImV4cCI6MjA1ODUyMDQ5MX0.GCt_AnHGjmLZcx_S5ZGIM-iIyjWHFj0Td_4GXs8xDqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);